# Adapted from https://serverless.zone/iot-with-the-serverless-framework-e228fae87be#.92dlyi8gk
service: iot-mapper
provider:
  name: aws
  runtime: nodejs6.3
  # Need to change the variable syntax to prevent this configuration file
  # conflicting with CloudFormation
  variableSyntax: '\${{([\s\S]+?)}}'
# get runtime variables from a file
custom: ${{file(./vars-${{opt:stage}}.yml)}}

# define the get readings function 
# and define the get location function
functions:
  checkSensorReading:
    handler: index.checkSensorReading
  getLocation:
    handler: index.getLocation

resources:
  Resources:
    # other resources that need declaration: DynamoDB, IoT
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: { Fn::GetAtt: [ checkSensorReading, getLocation, Arn ] }
        Action: lambda:InvokeFunction
        Principal: iot.amazonaws.com
